### ISSUE TITLE
Some errors when I applied to my application.

### ISSUE THREAD

**Issue by JAVaGKI** [OpenSourcePFCLibraries/2019#1]
Hi, I downloaded the zip file and applied it on my project, but it give me some errors on pfc_n_cst_dwsrv_grid and pfc_n_cst_dwsrv_find

pfcdwsrv\pfc_n_cst_dwsrv_grid of_populate
	li_rc = of_getobjects( ls_dwobject, "COMPUTE", "DETAIL", false, true) ----> Bad Number of arguments for function of_getobjects
	// 1.2 - Then append computed 
	li_rc = of_describe( ls_name, "#HEADERNAME#", ls_dwobject ) ----> Reference argument type does not match function definition
	// 1.4 - Get name of Dw objects
	li_rc = of_describe( ls_visible, "VISIBLE", ls_dwobject ) ----> Reference argument type does not match function definition 
	// 1.5 - Get Visible status of Dw objects
	li_rc = of_describe( ls_order, "X", ls_dwobject ) ----> Reference argument type does not match function definition
	// 1.7 - Get width of Dw objects
	li_rc = of_describe( ls_width, "WIDTH", ls_dwobject ) ----> Reference argument type does not match function definition

pfcdwsrv\pfc_n_cst_dwsrv_find Missing of_GetColumnEditStatus
	pfcdwsrv.pbl(pfc_n_cst_dwsrv_find)pfc_replace.0071:  ls_coleditstatus = of_GetColumnEditStatus(ls_colname, ll_currrow)
	pfcdwsrv.pbl(pfc_n_cst_dwsrv_find).of_find.0079:  ls_coleditstatus = of_GetColumnEditStatus(ls_colname, ll_rowfound)
 
On my app, I commented the errors and achieved run it with out problem.

If you need more information about the errors, please let me know.

Best regards
Juan Valdez

**Comment by bruce-armstrong** [comment]
I get absolutely clean compiles on the code.  Some of the functions you are referencing were added in the 12.5 version.  If you've got some objects in your own libraries that were copied in from a pre-12.5 version of PFC then those objects might be getting picked up instead of the 2019 version.
