### ISSUE TITLE
Different source in PBL and ws_objects

### ISSUE THREAD

**Issue by TABUllrich** [OpenSourcePFCLibraries/2019#2]
It seems that in PBL and ws_objects are differences in source.
In PBL is a newer version of pfc_n_cst_platform as in ws_objects.
see
is_ClassName[] = {"FNWND3190", "FNWNS3190"}
vs.
is_ClassName[] = {"FNWND3170", "FNWNS3170"}

I have not checked if other objects also have differences.

**Comment by bruce-armstrong** [comment]
Removed the old code outside of the ws_object folder.  It was left over from when the project was connecting to Github using an MSSCCI bridge.
