### ISSUE TITLE
pbdom objects in "2019/pfcapsrv" have references to "PBDOM170.pbx"

### ISSUE THREAD

**Issue by PBjole** [OpenSourcePFCLibraries/2019#9]
Example "pbdom_cdata" : global type pbdom_cdata from pbdom_text native "PBDOM170.pbx"

**Comment by TABUllrich** [comment]
There is a difference between Source in PBL directory and in ws_objects directory. Maybe it is because of change to native Git. (see issue #2)
The correct sources should be in ws_objects directory.

**Comment by bruce-armstrong** [comment]
Yes, the *.sr* files, the .pbg files and the directory-per-pbl structure are all remnants from when the project was using an MSSCCI bridge to talk to Git.  I'll remove the *.sr* files and .pbg files from the PBL directories.  I'm not going to change the directory structure at this time though.

**Comment by bruce-armstrong** [comment]
Ok, should be all cleaned up now.  Open another issue if you see something I missed.
